import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/features/header/container/header";
import localFont from 'next/font/local';
import {FooterText} from "@/features/footer/footer-text";

const myFont = localFont({
    src: [
        {
            path: "./fonts/SFProText-Light.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/SFProText-Medium.ttf",
            weight: "500",
            style: "normal",
        },
    ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} flex flex-col pt-[64px] items-center bg-[#010814] antialiased`}
      >
      <Header/>
        {children}
      <FooterText/>
      </body>
    </html>
  );
}
